### ISSUE TITLE
is it time for a new release into the asset store?

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#101]
Considering there's been some nice changes, I think its time to release this version to the asset store, right? ;)

**Comment by astrale-sharp** [comment]
As mentioned before by @arnaudgolfouse , I think @MatejSloboda has the rights the publish on the asset store and no one else right?

**Comment by astrale-sharp** [comment]
Its time we consider @MatejSloboda is dead :(
maybe it is COVID 19, studies, the opensource community, maybe he wasnt real in the first place! (maybe we'll never know).
I say we take the matter in our own hands
![peanutbutter](https://user-images.githubusercontent.com/53686698/110159860-8362aa00-7deb-11eb-80a0-f6a8cad80260.gif)

**Comment by dianegolfouse** [comment]
I see your coup is going well... :fearful:

**Comment by astrale-sharp** [comment]
Thanks so much to KohuGaly for sharing his accompt! The new release is pending for approval!

**Comment by astrale-sharp** [comment]
it's live!
