### ISSUE TITLE
InputMap already has action "left_mouse_button"

### ISSUE THREAD

**Issue by dianegolfouse** [MatejSloboda/Dijkstra_map_for_Godot#109]
This is really a small nitpick: when launching the main scene (visualisation.tscn), godot complains: 
```
E 0:00:00.705   add_action: InputMap already has action "left_mouse_button".
  <C++ Error>   Condition "input_map.has(p_action)" is true.
  <C++ Source>  core/input_map.cpp:89 @ add_action()
  <Stack Trace> gridmap.gd:14 @ _ready()
```
With my limited godot knowledge, I think this happen because we define "left_mouse_button" twice:
- Once, as the error says, in gridmap.gd, line 14;
- And also in the project's settings, in the InputMap panel.

Removing either one fixes the message (and all scenes keep working), I just don't know which one should be kept.

**Comment by astrale-sharp** [comment]
Solved in 237a13af11b3257b10353c6fe77eee17e10728ec
