### ISSUE TITLE
Windows Binaries for 3.5.1

### ISSUE THREAD

**Issue by goblinJoel** [MatejSloboda/Dijkstra_map_for_Godot#115]
Thanks for getting the repo code updated to support Godot 3.5!

Would it be possible to get Windows binaries for 3.5.1 updated and/or updated in the asset library?

I've never attempted to work with rust or gdnative, but if it's actually pretty straightforward to set up enough to compile this, I could try it and make a PR. (I'm not sure how much the instructions are glossing over or if you have to do things a certain way to make it work on other peoples' OS versions / CPU brands.)

---
If not, maybe we can update the instructions -- they are a little misleading:

The instructions recommend the asset library, but the github method notes you have to use github for 3.5.1. It says you can skip the rust install, gdnative dependencies, and compilation if you're on Windows, but the existing files might be "slightly outdated" (which in this case means they just won't work). So for 3.5.1, you have to skip the recommended route to see the github version's note, then notice that the binaries in the repo are pretty old, then figure out how to set up rust and gdnative.

**Comment by goblinJoel** [comment]
Messed with it myself to see if I could build the Windows dll based on the instructions in the readme, but after installing various things and trying to get it to `cargo build --release`, I'm hitting errors about libclang being missing. I didn't understand the instructions for godot-rust, so I probably missed something there. Fun stuff. I'll wait to see if anyone who already has this set up on Windows is able to do the updated build.

**Comment by astrale-sharp** [comment]
Hey! Do you have clang installed? If you don't that'll probably fix it ☺️

I actually tried compiling for Windows (from linux) but it doesn't work at the moment and i don't think it's been fixed!
If it doesn't work we can still compile with GitHub actions so just ask !
________________________________

**Comment by goblinJoel** [comment]
Oh, do you have a github action set up to generate these? Please do, that'd definitely be great!

Not sure what's involved in updating things in the repo itself or for the asset library, but it seems like those are the remaining steps for the 3.5.1 upgrade to be wrapped up. (At least for Windows users. I see there's another issue in this repo for Linux still.)

**Comment by astrale-sharp** [comment]
Not yet but that could be done, it would up the repositary size tho which i don't like... for now have you tried installing clang before building?
https://www.wikihow.com/Install-Clang-on-Windows

**Comment by astrale-sharp** [comment]
The asset library release is pending for approval ;)

**Comment by astrale-sharp** [comment]
Closing as the release is available on the asset store ! <3

**Comment by goblinJoel** [comment]
Confirming I was able to update to Godot 3.5.1 and update the addon via the AssetLib. Looks like it's working! Thanks, guys!

**Comment by astrale-sharp** [comment]
😇❤️
________________________________
