### ISSUE TITLE
Compatible with 3d environment? 

### ISSUE THREAD

**Issue by Dangomation** [MatejSloboda/Dijkstra_map_for_Godot#119]
Pathfinding is my worst skill and while skimming around the documentation and I was wondering if this might be used for 3d "AI" controlled pathfinding? lets just make an assumption the world is a 3d grid map for simplicity sake. 

I'd thought I ask smarter people before finding out the hard way.

**Comment by MatejSloboda** [comment]
Yes, the pathfinding algorithm works for any arbitrary graph, as long as the edges have positive weights. The graph is actually agnostic about what kind of "space" it represents. It may be 2D space, 3D space, non-euclidean geometries (ie. portals), or it might not be a geometric space at all (for example it could be used to find "cheapest tech progression" towards a certain tech in a tech tree).

**Comment by Dangomation** [comment]
Oh neat! thank you for the response! I guess its time to struggle on integrating this. 
I really struggled at using Godot AStar so lets see how this will end up.

**Comment by astrale-sharp** [comment]
Closing for now since the question seems resolved ;)
