### ISSUE TITLE
replace all recalculate_* methods with a single method, that takes parameters as a dictionary

### ISSUE THREAD

**Issue by MatejSloboda** [MatejSloboda/Dijkstra_map_for_Godot#13]
The number of potentially optional parameters keeps growing. I think it might be better to replace all the recalculate_* methods with a single one. It will have one mandatory parameter (the target, which could be either Int or PoolIntArray) and then a dictionary for the optional parameters. If entries are absent in the dictionary, they'd be assumed to be default values
example:
old:
recalculate_for_targets_with_costs(targets,initial_costs,max_cost,reversed)
all parameters are mandatory at the moment.
new:
recalculate(targets, {"initial costs":initial_costs, "maximum cost":max_cost,"reversed":reversed} )
All entries in the second argument (the dictionary) are optional. If absent, default values are assumed.

**Comment by astrale-sharp** [comment]
I also think this is of better usability

**Comment by astrale-sharp** [comment]
should I try to deal with that or are you on it?

**Comment by MatejSloboda** [comment]
Already working on it. Rust is very bureaucratic when it comes to optional/multiple-option values. It takes time.
