### ISSUE TITLE
initialize as grid should returns id_dictionnary -> pos_dictionnary

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#21]
Hey, that would be nice otherwise it means the end user must do some calculus, look at the rust code etc

**Comment by MatejSloboda** [comment]
You are right. It should spit out position->ID dictionary or vice versa. The description of the method says that ID encodes the coordinates, and shows how to convert ID to (x,y) and vice versa, but we don't have public documentation to make that absolutely clear.

**Comment by astrale-sharp** [comment]
yea, plus I tried a bit to use it and failed pathetically :D (hence the broken demo) ;)

**Comment by astrale-sharp** [comment]
I'm working on that now
