### ISSUE TITLE
should add_point have default terrain arg?

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#25]
if you don't want to bother about terrains, it might be useful to have a id == -1 with weight always == 1.0
so you can pass only the id argument

(if the user try to pass that id, it would be good to throw an error)

just an idea to make the API more usable, what do you all think, crowd of people? ;)

**Comment by MatejSloboda** [comment]
Great idea. However, we should still allow user to use the ID=-1. In case they specifically want to restore the point to default terrain. Having it mentioned that the argument defaults to -1 should be sufficient.
That raises another question though. Should we allow the user to provide weight for the default terrain in the recalculate() method?

**Comment by astrale-sharp** [comment]
I don't think so, default to 1.0 is great (cause neutral), if this damn user wants anything more, he can use the 2^32 - 2 other int32 available to set the terrain of their wildest dreams !

**Comment by astrale-sharp** [comment]
I misread your comment, yea, i totally agree!
