### ISSUE TITLE
rust : recalculate method : optionals_args should default to empty set 

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#26]
so has to go with defauts when you don't  pass a dict, better usability ;)

**Comment by MatejSloboda** [comment]
I don't know how to implement optional arguments in rust that godot would recognize.

**Comment by astrale-sharp** [comment]
ah yes! I'll call my rust friends tomorrow maybe they know something, I'll get back to you here on that

**Comment by astrale-sharp** [comment]
Okay so here's what my rust friend (its singular today) found out : 
gdnative = "0.8" does'nt support optional argument
gdnative = { git = https://github.com/GodotNativeTools/godot-rust } 
does, (but Im unsure of the stability of this, it always points to their master branch so, each time they merge a commit it might break something, but they seem pretty serious and we'll have unit test so it might be worth to do that)

and then by replacing
`
pub fn recalculate(&mut self, mut _owner: gdnative::Node, target: gdnative::Variant, optional_params: gdnative::Dictionary)
`
by
`pub fn recalculate(&mut self, mut _owner: gdnative::Node, target: gdnative::Variant, #[opt] optional_params: gdnative::Dictionary)
`
it should work, I have work this afternoon so I'll test that tomorrow, what do you think about using : gdnative = { git = https://github.com/GodotNativeTools/godot-rust }  ? :)

**Comment by dianegolfouse** [comment]
Hi, you can also specify a specific commit, like so : 
`gdnative = { git = https://github.com/GodotNativeTools/godot-rust, rev = 4195027a74fc46f20c33d74a92e15494217a2d1c`

**Comment by MatejSloboda** [comment]
Great, thanks for the info. I knew I read somewhere about the #[opt] thing and was confused when it didn't work. This explains why. Yes, I think we should move to more recent version of godot-rust. The optional argument is a big thing.
