### ISSUE TITLE
rust : connect_points : bidirectionnal should default to false ?

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#27]
all of theses are open to discussion, if you also think it is a good idea, i can take care of them (at least that one is simple)

**Comment by MatejSloboda** [comment]
It should default to true, to keep it consistent with how connect_points behaves in native [AStar class.](https://docs.godotengine.org/en/3.1/classes/class_astar.html#class-astar-method-connect-points)
