### ISSUE TITLE
default args

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#31]
are you dealing with this?
I'll fix the unittest in the meantime, if you're not, next thing I do is get optionals arguments for reculaculate {}, bidirectionnal true, defaut terrain -1

**Comment by MatejSloboda** [comment]
Not at the moment, as I was rather busy lately.

**Comment by astrale-sharp** [comment]
ok Im starting to work on it; leave it to me :p
