### ISSUE TITLE
Default behavior of recalculate() method changed

### ISSUE THREAD

**Issue by MatejSloboda** [MatejSloboda/Dijkstra_map_for_Godot#36]
I've changed the default behavior of the `recalculate()` method. Now it treats the input as an origin/source. The "reversed" option was renamed to "input is destination" and it's behavior is opposite.
I've decided on a minor change in terminology. The point where path starts will be referred to as "origin" (previously we called it source) and the point where path ends will be referred to as "destination" (previously we called it target). It is a bit more clear now.
recalculate_for_target* methods are now deprecated, as they can easily be replicated with recalculate() method with appropriate optional arguments. They will be removed in upcoming commits once they are fully removed from examples and tests (I tried my best to remove them already).

upcoming features:
"terminate at" -> point_ids option for recalculate()
gives the method an option to terminate mapping once it reaches one of specified points. This will allow us to use DijkstraMap for regular pathfinding, like Astar.

**Comment by astrale-sharp** [comment]
Nice, Its for the best, its gonna be clearer to have this one method with this name
