### ISSUE TITLE
could I get the right to set label as well? :) might be a little bit cleaner 

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#38]

**Comment by MatejSloboda** [comment]
I've set you as a collaborator. Hope that works.

**Comment by astrale-sharp** [comment]
oh thank you ;)
EDIT: it doesnt work though ^^'

**Comment by MatejSloboda** [comment]
It says I've send you an invite and it's waiting for your response. Check if you have notification or something like that.

**Comment by astrale-sharp** [comment]
Ah it was in my mail, what a weird workflow ;) 
thank you very much :)
