### ISSUE TITLE
it looks near completion to me

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#44]
what do you think? more features idea? we've got 2 demos, some tests, I'll write some more to illustrate add-square-grid etc
apart from that it looks finished to me, should we try to put it in the asset store?

**Comment by MatejSloboda** [comment]
It is near completion. I have 2 more features to add. Namely, an option to supply `Shape2D` or `BitMap` for the `bounds` argument in add_*_grid() methods. And option pull graph from existing Astar/Astar2D object. Possibly even vice versa (though that might prove impossible).

**Comment by MatejSloboda** [comment]
One thing to figure out is how to compile it for all systems. If we put it in the asset store, it'd be nice if it worked right off the bat, no compiling needed.

**Comment by astrale-sharp** [comment]
yea I agree!
I can compile for linux only, that said, finding a windows user cant be this difficult ;)

**Comment by astrale-sharp** [comment]
ouh, yea these would be very nice !

**Comment by MatejSloboda** [comment]
I've seen somewhere that you can specify a target system in the rust compiler. I have not tested it yet. Guys over at the GDNative Rust github are putting together a documentation where all of this will be explained. I think we might ask them.

**Comment by MatejSloboda** [comment]
OK, the Shape2D input doesn't work. Neither does dumping from/to AStar.

I think we may have a final version now. The only thing missing is good documentation.

**Comment by astrale-sharp** [comment]
hmm, 
* should we build the doc with cargo and put it in the project? 
or you have another idea? ^^

**Comment by MatejSloboda** [comment]
I'm not sure. Rustdocs use rust syntax and shows rust types. That may be rather confusing for the users. I was thinking of copying all the documentation to an .md file.

**Comment by astrale-sharp** [comment]
thats a good idea, I'm on it!
