### ISSUE TITLE
im working on compiling for windows from linux

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#49]
it should come soon but no way to test it

**Comment by MatejSloboda** [comment]
I'm on windows, so I can compile it and test it if you want.

**Comment by MatejSloboda** [comment]
The windows compile did not work. I replaced it with mine

**Comment by astrale-sharp** [comment]
Ah you did well ! I'm gonna remove some artefact of my try in the .toml
