### ISSUE TITLE
recalculate_* should cause engine crash if passed Vector2 instead of id

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#5]
currently it silently fails
it would be of better usability if obdvius common bad behaviours like this crashed

This I have no idea how to fix, if someone guides me, I'll see what I can do

**Comment by MatejSloboda** [comment]
This is the same issue like with the connect_points method. Godot simply longs an argument error (in the debugger, not the output), returns null and then moves on as if nothing happened. This is handled by the GDNative API. One way to fix it is to expect all arguments as Variant type, try to convert them to appropriate value and manually raise an error if argument is invalid.
