### ISSUE TITLE
publishing to the asset store

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#52]
Okay, what do you think of the following/help for improve it (its not over anyway)

Asset Name:
pathfinding Dijkstra Map EDIT
    Category:
Script
    Godot version:
3.2
    Version:
1.0
    Repository host:
Github
    
Repository URL:
https://github.com/MatejSloboda/Dijkstra_map_for_Godot/
    Download Commit/Tag:
        I will make a branch v1.0 and use that commit : c696c34d18a8af413aa91eb1286e06448a6420cc
    Icon URL:
    License:
MIT
    Description:
The main feature of this project is that it calculates shortest paths and their costs over the entire graph, not just a single path between two points. EDIT

**Comment by MatejSloboda** [comment]
Name should be pathfinding Dijkstra Map. The main feature of this project is that it calculates shortest paths and their costs over the entire graph, not just a single path between two points.

**Comment by astrale-sharp** [comment]
Ah, we need an icon apparently !

**Comment by MatejSloboda** [comment]
@astrale-sharp I've added new visualization demo. It's similar to the api demo, but a little bit more clear IMHO. We might use screenshot from that as an icon.

**Comment by MatejSloboda** [comment]
added the candidate for an icon (dm_icon.png). Is it OK?

**Comment by MatejSloboda** [comment]
Seems about right. 
Icon URL: https://raw.githubusercontent.com/MatejSloboda/Dijkstra_map_for_Godot/master/dm_icon.png

The description may be re-worded to be more descriptive:
A more feature-rich alternative to AStar. Main feature is the ability to pre-compute paths from given origin point to all points, which can then be easily accessed.

If this is OK, I may submit it this evening.

**Comment by astrale-sharp** [comment]
Its okay! :)
I let you submit it then!

**Comment by MatejSloboda** [comment]
submitted... waiting for approval.
