### ISSUE TITLE
broken methods

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#63]
The 'duplicate_graph_from' 
'add_grid_internal'
'add_hexagonal_grid'
'add_square_grid' methods got broken

**Comment by astrale-sharp** [comment]
im on documenting that it doesnt work anymore, if i get some time i'll try to fix theses methods

**Comment by MatejSloboda** [comment]
It seems I have fixed it. The issue was, there was a change in "0.9.0" in how Dictionary is accessed and how NativeScript instances are casted and accessed.
