### ISSUE TITLE
use modules to split the code into more idiomatic rust

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#64]
Discussion, in what modules could we split up the code ?
then i'd like to do the splitting

**Comment by MatejSloboda** [comment]
The only sensible thing I can think of is splitting up the methods that modify the graph ( `add_point()`, `connect_points()`, `add_square_grid` etc.), methods that recalculate the Dijkstra map ( `recalculate()` ) and methods that read out results ( `get_direction_at_point()`, `get_cost_at_points()` etc. ). That's kinda how they are split up in the documentation too.

**Comment by astrale-sharp** [comment]
i have pupt my ideas in motion, i close this issue and open a more appropriate one
