### ISSUE TITLE
Change DijkstraMap superclass from Node to Reference

### ISSUE THREAD

**Issue by MatejSloboda** [MatejSloboda/Dijkstra_map_for_Godot#66]
At the moment DijkstraMap inherits from Node. This is unnecessary, since it's not intended to be inserted into scene tree. It should be used as a Reference object in code, just like AStar and AStar2D nodes.

**Comment by astrale-sharp** [comment]
Agreed, I can deal with this next week

**Comment by MatejSloboda** [comment]
I've already included this change in my latest commit. It needed minor changes to the GDScript examples, to remove the manual dijkstra_map.free() call, that were necessary for node.
