### ISSUE TITLE
idiomatic code/ splitting code/etc

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#67]
Hey, look at my fork, i broke everything!
i splitted code in multiple files
in the godot_interface module, you can see the class beeing passed to godot *it is broken right now but i'll fix it soon*
the rest of the rust code can now be tested (as you can see running cargo test)
which is useful for integrating it with more rust code which is what i want to do
i tried to write more idiomatic rust code

its a work in progress but i think its the right way to go, you're invited to help if you'd like, i think i will have fixed everything tomorrow

**Comment by MatejSloboda** [comment]
yeah, it's an improvement as far as readability is concerned from rust perspective.

**Comment by astrale-sharp** [comment]
so it is complete again! but i cant push because i messed with the history!
I created a new repository here! https://github.com/astrale-sharp/Godot-DijkstraMap-rust
you can pull --force if you'd like

**Comment by astrale-sharp** [comment]
#68 I'll let you look and decide as there is a lot of changes but everything works ;)

**Comment by MatejSloboda** [comment]
Wow, this is impressive work right there. I'll have to compile it to add the binary for Windows.
