### ISSUE TITLE
no binary for windows

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#71]
need to compile for windows and connect it in the gdnativelibrary resource

**Comment by MatejSloboda** [comment]
I've run into some issues. The `turn_based.tscn` example project does not work. The `get_shortest_path_from_point` always returns empty array, for some reason. I'm trying to figure out what the issue is.

**Comment by MatejSloboda** [comment]
Fixed it. There was a typo in the method, that caused it to break out of loop instantly. Added the windows DLL. Please re-compile the linux version
