### ISSUE TITLE
      find a way to compile it to all platforms in order to ship it via the godot asset store

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#77]
Im having a hard time trying to cross compile, if anyone knows how to do so with cargo, it would be helpful

**Comment by dianegolfouse** [comment]
Cross compilation have recently been achieved ! :tada:  (see PR #85)

**Comment by MatejSloboda** [comment]
I've updated the download commit in the Godot AssetLib, pending approval by moderators. Once it goes live, this issue may be closed. Agreed?

**Comment by MatejSloboda** [comment]
Asset approved! I'm closing this issue.
