### ISSUE TITLE
Fix: Turn Based Example Build Fix

### ISSUE THREAD

**Issue by SimonasLetukas** [MatejSloboda/Dijkstra_map_for_Godot#84]
Hello,

Currently Project Example/dependancy/turn_based is not building. I'd like to open a PR but it looks like I don't have a permission to push my branch to remote. All I did was change `id` to `point_id` in turn_based.gd lines 45 & 46. 

Seems like this issue is present in 1.0 branch as well.

**Comment by dianegolfouse** [comment]
Hi !

I tried cloning the `master` branch and doing the change the change you described (change `id` to `point_id` in turn_based.gd lines 45 & 46), and everything worked ; are you sure you cloned the right branch ? Branches other than `master` might be outdated / not work.

Also, what is your os ? I think that `Dijkstra_map_library/bin/windows/dijkstra_map_gd.dll` is really outdated, so if you're on windows you should wait until we update it (hopefully soon), or build it yourself.

**Comment by SimonasLetukas** [comment]
Yes, I'm on Windows. Yeah, changing the stuff works for me as well, I was talking about pushing a PR with the fix so it could be merged to master or even 1.0 branch, as the issue is on the 1.0 branch as well. It says I don't have the permissions to push my branch with the fix and open a PR, so tough luck :D

**Comment by dianegolfouse** [comment]
Oh ok ! I don't know how familiar you are with this process so I will try to describe it precisely :
- fork the `MatejSloboda/Dijkstra_map_for_Godot` repository
- clone `SimonasLetukas/Dijkstra_map_for_Godot` on your computer, make the changes you want to make here
- push (it should push to `SimonasLetukas/Dijkstra_map_for_Godot` by default)
- Create a pull request from `SimonasLetukas/Dijkstra_map_for_Godot`
- wait for changes to be accepted :slightly_smiling_face: 

Hope this helps you !

**Comment by astrale-sharp** [comment]
Hey there, i don't understand the problem exactly : gdscript doesnt need compilation (it doesnt build) so what is this problem exactly?
much love,
Ash

**Comment by SimonasLetukas** [comment]
Opened PR: #86
