### ISSUE TITLE
Should we forwards the example in the asset store?

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#97]
Other's project don't so I think its okay to not do that, what do you all think?

**Comment by MatejSloboda** [comment]
Yes, perhaps we should separate the actual project and the examples. Maybe provide a link to a repo with examples in the description? I'm not quite sure how we should handle it. I'm also not in love with how the source code is separated from the binaries. Maybe we should put the source code directories into the _/addons/dijkstra-map/Dijkstra_map_library/_ and put `.gdignore` file in them to prevent Godot from importing them.

**Comment by astrale-sharp** [comment]
we currently use .gitattributes to ignore files on zip export (which is what is used by the asset-lib so thats very useful), we could move the source code wherever you want and use this to not export it.
But i think its fine to have the examples in the same project as long as we dont export them in the assetlib (which is the current behavior)

**Comment by MatejSloboda** [comment]
I agree

**Comment by astrale-sharp** [comment]
closing this then ;)
